#!/bin/bash

xsetroot -cursor_name left_ptr
picom -b
dunst &
~/.fehbg &
echo -e "power on\nscan on\n" | bluetoothctl &
xautolock -time 20 -locker slock -killer "systemctl suspend" -killtime 30 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5

bspc config focused_border_color '#FD841F'
bspc config normal_border_color  '#454545'
bspc config active_border_color  '#FD841F'

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a feh state=floating
bspc rule -a Spotify desktop=^10 follow=off
bspc rule -a Thunar desktop=^9 follow=on
bspc rule -a firefox desktop=^1 follow=on

## Scratchpad
bspc rule -a scratchst sticky=on state=floating hidden=on locked=on
bspc rule -a notes sticky=on state=floating hidden=on locked=on
# check scratchpad already running
[ "$(ps -x | grep -c 'alacritty --class scratchst')" -eq "1" ] && alacritty --class scratchst -o window.dimensions.columns=300 window.dimensions.lines=60 -e /usr/bin/zsh &
[ "$(ps -x | grep -c 'alacritty --class notes')" -eq "1" ] && (cd ~/Notes && alacritty --class notes -o window.dimensions.columns=300 window.dimensions.lines=60 -e o) &
